<script lang="ts">
    import Navbar from "./lib/Navbar.svelte";
    import Content from "./lib/Content.svelte";
    import Card from "./lib/Card.svelte";
    import Footer from "./lib/Footer.svelte";
    import SubsectionLink from "./lib/SubsectionLink.svelte";
    import MobileNavigation from "./lib/MobileNavigation.svelte";

    let text_section = "Feedback";
    let image_section = "Visualize";
    let mobile_nav_open = false;
    let innerWidth = 0;
</script>

<svelte:window bind:innerWidth />

<svelte:head>
    <title>Ai Edu</title>
</svelte:head>

<Navbar bind:mobile_nav_open />

{#if innerWidth < 720}
<MobileNavigation bind:mobile_nav_open />
{/if}

<Content>
    <h1 class="title">A new age of education</h1>
    <img class="hero-img" src="images/hero.png" alt="Ai generated" />
    <p class="hero-img-credit">Generated by OpenAI’s DALL-E 2</p>

    <section id="text-generation">
        <h2 class="header">Text Generation</h2>
        <div class="subsection-links">
            <SubsectionLink
                name="Feedback"
                bind:current_selection={text_section}
            />
            <SubsectionLink
                name="Planning"
                bind:current_selection={text_section}
            />
            <SubsectionLink
                name="Learning"
                bind:current_selection={text_section}
            />
            <SubsectionLink
                name="Research"
                bind:current_selection={text_section}
            />
        </div>

        <div class="cards">
            {#if text_section === "Feedback"}
                <Card
                    title="Instant Feedback"
                    description="Instant feedback helps students progress quicker and learn from their mistakes"
                />
                <Card
                    title="Motivate Students"
                    description="Feedback builds confidence in students abilities and increase their desire to learn more"
                />
            {/if}
        </div>
    </section>

    <section id="image-generation">
        <h2 class="header">Image Generation</h2>
        <div class="subsection-links">
            <SubsectionLink
                name="Visualize"
                bind:current_selection={image_section}
            />
            <SubsectionLink
                name="Imerse"
                bind:current_selection={image_section}
            />
            <SubsectionLink
                name="Accessibility"
                bind:current_selection={image_section}
            />
            <SubsectionLink
                name="Engage"
                bind:current_selection={image_section}
            />
        </div>

        <div class="cards">
            {#if image_section === "Visualize"}
                <Card
                    title="Visual Aids"
                    description="AI can help students visualize concepts and make them more concrete and understandable"
                />
                <Card
                    title="Quickly"
                    description="Teachers can quickly create custom images and diagrams that meet their teaching needs"
                />
            {/if}
        </div>
    </section>
</Content>

<Footer />

<style>
    .title {
        width: 100%;
        font-size: 2.5rem;
        font-weight: 800;
        text-align: center;
        text-transform: uppercase;
    }

    .hero-img {
        width: 100%;
        border-radius: 20px;
        margin-top: 60px;
    }

    .hero-img-credit {
        width: 100%;
        font-size: 16px;
        font-weight: 600;
        text-align: center;
        margin: 8px 0;
    }

    section .header {
        width: 100%;
        font-size: 32px;
        font-weight: 700;
        text-align: center;
        margin-top: 60px;
    }

    section .subsection-links {
        display: flex;
        gap: 40px;
        font-weight: 600;
        font-size: 18px;
        overflow: scroll;
        -ms-overflow-style: none;
        scrollbar-width: none;
        margin-bottom: 20px;
    }

    .subsection-links::-webkit-scrollbar {
        display: none;
    }

    section .cards {
        display: flex;
        flex-direction: column;
        gap: 20px;
    }
</style>
