<script lang="ts">
    import Card from "./lib/Card.svelte";
    import SubsectionLink from "./lib/SubsectionLink.svelte";
    import TryIt from "./lib/TryIt.svelte";

    let text_section = "Feedback";
    let image_section = "Visualize";
</script>

<svelte:head>
    <title>Ai Edu</title>
</svelte:head>

<div class="hero">
    <h1 class="title">A new age of education</h1>
    <div class="hero-img-container">
        <img class="hero-img" src="images/hero.webp" alt="Ai generated" />
        <p class="hero-img-credit">Generated by OpenAI’s DALL-E 2</p>
    </div>
</div>

<!-- <section id="about">
    <h2 class="header">What is AI?</h2>
    <p>
        Artificial Intelligence, or AI, is a type of computer technology that is
        designed to do things that usually require human intelligence, such as
        solving problems and making decisions. It is like a smart robot that can
        learn new things and think on its own. AI is becoming more important in
        many areas of our lives, including education. This technology has the
        potential to change the way we learn and teach in the future.
    </p>
</section> -->

<section id="text-generation">
    <h2 class="header">Text Generation</h2>
    <div class="subsection-links">
        <SubsectionLink name="Feedback" bind:selection={text_section} />
        <SubsectionLink name="Planning" bind:selection={text_section} />
        <SubsectionLink name="Learning" bind:selection={text_section} />
        <SubsectionLink name="Research" bind:selection={text_section} />
    </div>

    <div class="cards">
        {#if text_section === "Feedback"}
            <Card
                title="Instant Feedback"
                description="Instant feedback helps students progress quicker and learn from their mistakes"
                image="images/feedback.webp"
            />
            <Card
                title="Motivate Students"
                description="Feedback builds confidence in students abilities and increase their desire to learn more"
                image="images/modivate.webp"
            />
        {/if}
    </div>
</section>

<section id="quick-generation">
    <div>
        <h2>It's fast!</h2>
        <p>Generate text instantaneously and images in seconds</p>
    </div>
    <img
        src="images/stopwatch.webp"
        alt="ai generated stopwatch"
        loading="lazy"
    />
</section>

<section id="image-generation">
    <h2 class="header">Image Generation</h2>
    <div class="subsection-links">
        <SubsectionLink name="Visualize" bind:selection={image_section} />
        <SubsectionLink name="Imerse" bind:selection={image_section} />
        <SubsectionLink name="Accessibility" bind:selection={image_section} />
        <SubsectionLink name="Engage" bind:selection={image_section} />
    </div>

    <div class="cards">
        {#if image_section === "Visualize"}
            <Card
                title="Visual Aids"
                description="Need to picture a chicken standing on an elephant? AI can do that!"
                image="images/elephant.webp"
            />
        {/if}
    </div>
</section>

<section id="try-it">
    <h2 class="header">Don't belive me?</h2>
    <h3>Ask the AI a question</h3>
    <TryIt />
</section>

<style>
    .hero {
        display: flex;
        flex-direction: column;
        gap: 3rem;
    }

    .title {
        width: 100%;
        font-size: 2.2rem;
        font-weight: 700;
        text-align: center;
        text-transform: uppercase;
    }

    .hero-img {
        width: 100%;
        border-radius: 20px;
    }

    .hero-img-credit {
        width: 100%;
        font-size: 16px;
        text-align: center;
        margin: 8px 0;
    }

    section {
        margin-top: 6rem;
    }

    section .header {
        width: 100%;
        font-size: 2rem;
        font-weight: 700;
        text-align: center;
        margin-top: 60px;
    }

    section .subsection-links {
        display: flex;
        gap: 40px;
        font-weight: 600;
        font-size: 18px;
        margin: 0 auto;
        max-width: fit-content;
        margin-bottom: 2rem;
        overflow: scroll;
        -ms-overflow-style: none;
        scrollbar-width: none;
    }

    .subsection-links::-webkit-scrollbar {
        display: none;
    }

    section .cards {
        display: flex;
        flex-direction: column;
        gap: 20px;
    }

    #quick-generation {
        background: #ff7f5f;
        padding: 1rem;
        color: white;
        border-radius: 20px;
        text-align: center;
        display: flex;
        flex-direction: column;
        max-width: 800px;
    }

    #quick-generation img {
        width: 100%;
    }

    #try-it h2 {
        margin-bottom: 0.5rem;
    }

    #try-it h3 {
        width: 100%;
        font-size: 1.2rem;
        text-align: center;
        font-weight: 500;
        margin-top: 0;
        margin-bottom: 3rem;
    }

    @media only screen and (max-width: 330px) {
        .title {
            font-size: 1.8rem;
        }
    }

    @media only screen and (min-width: 400px) {
        .hero {
            gap: 1rem;
        }

        .title {
            font-size: 2.5rem;
        }

        .hero-img {
            max-width: 350px;
            display: block;
            margin: 0 auto;
        }

        #quick-generation {
            padding: 1rem 2rem;
        }
    }

    @media only screen and (min-width: 600px) {
        #quick-generation {
            flex-direction: row;
            text-align: left;
            align-items: center;
        }

        #quick-generation h2 {
            font-size: 2rem;
        }

        #quick-generation img {
            max-width: 300px;
        }
    }

    @media only screen and (min-width: 700px) {
        section .header {
            font-size: 2.5rem;
        }

        section .cards {
            flex-direction: row;
        }
    }

    @media only screen and (min-width: 900px) {
        .hero {
            margin-top: 4rem;
            flex-direction: row;
            align-items: center;
        }

        .title {
            text-align: left;
            width: 50%;
            font-size: 3rem;
            min-width: 400px;
        }

        .hero-img {
            max-width: 400px;
        }

        #quick-generation {
            padding: 1rem 6rem;
        }

        #quick-generation h2 {
            font-size: 2.5rem;
        }

        #quick-generation p {
            font-size: 1.2rem;
        }

        #quick-generation img {
            max-width: 350px;
        }
    }

    @media only screen and (min-width: 1200px) {
        .hero {
            gap: 3rem;
        }

        .title {
            font-size: 3.8rem;
        }
    }
</style>
