<footer>
    <h4>The new way to teach</h4>
    <p>
        All images generated by AI.
        <br />
        DALLE 2, Midjourney and Bing Image Creator.
    </p>
    <p>
        Most text generated by OpanAI's Chat-GPT.
    </p>
    <p>Copyright© 2023 Liam Gallagher. All rights reserved.</p>
</footer>

<style>
    h4,
    p {
        margin: 0;
    }

    footer {
        background: #f4f4f4;
        padding: 20px 30px 10px;
        margin-top: 60px;
        padding-bottom: 20px;
    }

    h4 {
        width: 100%;
        font-weight: 500;
        font-size: 1.5rem;
        text-align: center;
    }

    p {
        width: 100%;
        margin-top: 12px;
        font-size: 12px;
        text-align: center;
    }
</style>
